<?php
/**
 * @var $block \Inclusive\WebinarsEvents\Block\Category\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
/** @var Inclusive\WebinarsEvents\Helper\Event $_eventHelper */
$_eventHelper = $this->helper('Inclusive\WebinarsEvents\Helper\Event');

$totalItems = count($_productCollection);
$callToActionPos = 9;
if ($totalItems < 8) {
    $callToActionPos = 0;
}
if($_eventHelper->showToolbar($_productCollection)) {
    $callToActionHtml = $block->getChildHtml('call-to-action-wrapper');
} else {
    $callToActionHtml = '';
}
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php if($_eventHelper->showToolbar($_productCollection)): ?>
        <?= $block->getToolbarHtml(); ?>
    <?php else: ?>
        <div class="toolbar toolbar-products">
            <p class="toolbar-amount" id="toolbar-amount">
                <?php echo __('Displaying %1 Results',
                    '<span id="shown-items-count" class="toolbar-number">' . $totalItems . '</span>') ?>
            </p>
        </div>
    <?php endif; ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_event_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?> inclusive-webinar-category-wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $name = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                <?php $name = $block->stripTags($name, null, true); ?>
                <?php if($iterator == $callToActionPos && $callToActionHtml): ?>
                    <li class="item category-action full-width">
                        <?= $callToActionHtml; ?>
                    </li>
                <?php endif; ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="product photo product-item-photo" tabindex="-1">
                            <img src="<?= $productImage->getImageUrl() ?>" alt="">
                        </div>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <?= $name ?>
                            </strong>
                            <div class="webinar-next-date">
                                <i class="icon-calendar"></i><?= $_eventHelper->getNextEventDate($_product); ?>
                            </div>
                        </div>
                    </div>
                </a>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
            <?php if($callToActionPos == 0 && $callToActionHtml): ?>
                <li class="item category-action full-width">
                    <?= $callToActionHtml; ?>
                </li>
            <?php endif; ?>
        </ol>
    </div>
    <?php if($_eventHelper->showToolbar($_productCollection)): ?>
        <?= $block->getToolbarHtml(); ?>
    <?php endif; ?>
<?php endif; ?>
